version: "2"
services:
  node:
    build:
      context: .
    restart: unless-stopped
    environment:
      - PRERENDER_SERVICE_URL=http://rendertron:3000/

  rendertron:
    build: https://github.com/mmjee/prerender-alpine.git
    restart: unless-stopped

